# Generated by Django 3.2.25 on 2024-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=45)),
                ('field_customer_phonenumber', models.CharField(db_column=' customer_phonenumber', max_length=45)),
                ('customer_dateofbirth', models.DateField(blank=True, null=True)),
                ('customer_gender', models.CharField(max_length=45)),
                ('customer_username', models.CharField(max_length=45)),
                ('customer_password', models.IntegerField()),
                ('customer_address', models.CharField(max_length=45)),
                ('customer_city', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
