# Generated by Django 3.2.25 on 2024-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegister',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=45)),
                ('staff_address', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('staff_phonenumber', models.CharField(max_length=45)),
                ('staff_dateofbirth', models.CharField(max_length=45)),
                ('staff_gender', models.CharField(max_length=45)),
                ('staff_email', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.IntegerField()),
            ],
            options={
                'db_table': 'staff_register',
                'managed': False,
            },
        ),
    ]
