# Generated by Django 3.2.25 on 2024-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('product_photo', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.FloatField()),
                ('manufacturer_date', models.CharField(max_length=45)),
                ('product_experity', models.CharField(max_length=45)),
                ('additional_description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
