# Generated by Django 3.2.25 on 2024-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('checkout_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'checkout',
                'managed': False,
            },
        ),
    ]
